### PR TITLE
Add fancontrol to vcu108 compute_tile example.

### PR DESCRIPTION
**Pull request by koenenwmn**

### CODE REVIEW

**Comment by imphil** [comment]
Looks good in general, however needs the fusesoc_cores changes first and then an update_externals.sh run. Let's wait until those changes are in.

**Comment by wallento** [comment]
lgtm, is this a replacement for #106?

**Comment by imphil** [comment]
Yes, it's the split-up version for the two separate repositories.

**Comment by wallento** [comment]
awesome, that's how a read it, thanks!

**Pull request merged**
