### PR TITLE
Fix system 2x2 cccc vcu108

### PR DESCRIPTION
**Pull request by koenenwmn**
Moved the Xilinx IPs from `src/soc/hw/xilinx_ip/` to the `system_2x2_cccc_nexys4ddr` example, created new ones for the `system_2x2_cccc_vcu108` example and fixed the DDR address widths for that example.  
Hope I didn't forget anything, let's see what Travis has to say..

### CODE REVIEW

**Comment by koenenwmn** [comment]
Seems to work in Travis and I just checked it again on the vcu108.  
Should I merge it like this or do you have any remarks @imphil @wallento ?

**Comment by imphil** [comment]
Travis doesn't test on FPGA, so that's expected to succeed :-) Please merge and we'll see if the next nightly build with FPGA builds works.

**Comment by imphil** [comment]
And maybe do a quick grep to make sure that no other file uses these IP blocks (if you haven't done that already)

**Comment by imphil** [comment]
I started a new build pipeline run, let's see how the FPGA builds are doing.

**Pull request merged**
