### PR TITLE
Fix problems found by SpyGlass lint

### PR DESCRIPTION
**Pull request by imphil**
Explicitly set file type to SV-2009 if we use localparam inside the
ANSI-style ports list, as this is the first version which supports this.

### CODE REVIEW

**Comment by wallento** [comment]
lgtm, lets wait for travis, then merge

**Comment by imphil** [comment]
Let's see how the travis python problem manifests on master

**Comment by wallento** [comment]
I identified it already, its unrelated (the python lib does not know the DEM-UART module I think) and I will fix it soon

**Comment by imphil** [comment]
Ah ok.

**Pull request merged**
