### PR TITLE
Add version checks

### PR DESCRIPTION
**Pull request by imphil**

### CODE REVIEW

**Comment by wallento** [comment]
This one broke the website build: https://hosting.librecores.org/blue/organizations/jenkins/OpTiMSoC/detail/OpTiMSoC/13/

We also need an update to the web repo, right?

**Comment by imphil** [comment]
Ah, the website build isn't using the Makefile. I'll fix it later today.

**Comment by wallento** [comment]
Let me update the builder then

**Comment by wallento** [comment]
Ah, it needs an update to the `build-docs.sh`. Will keep that to you then!

**Pull request merged**
