### PR TITLE
Lower timeout increments in libmp

### PR DESCRIPTION
**Pull request by koenenwmn**
I believe the timeout in libmp should be increased at a slower rate and also be restored to it's original value after a successful transaction.  
I ran the hello_mp example in a 3x3 system and, although it eventually finishes, it runs for tens of millions of cycles with the current timeout increase. With the proposed rate it finishes in ~400k cycles.

### CODE REVIEW

**Comment by wallento** [comment]
Hi, let's please not touch the old code. There is a massive update coming to that one. I will push it to a branch asap. Cheers, Stefan

**Comment by koenenwmn** [comment]
Then I guess it's also best if I postpone my work on #167 since this would include making adjustments on the baremetal libraries?

**Comment by imphil** [comment]
Well, if you have a need to get things fixed *right now*, I don't see a reason not to take this PR or similar ones. On the other hand, a major cleanup effort that doesn't give you solutions to immediate problems is probably best deferred. 

We all know how long "I'll open a PR soon" can be away.

**Comment by wallento** [comment]
Please also fix it in the mp_redesign branch then.

@koenenwmn please have a look at this branch, I suggest you start working on this instead of master

**Comment by koenenwmn** [comment]
It's nothing in my critical path at the moment, just came across it when I tried to run the example on a 3x3 system. Same for #167.  
Thanks @wallento, I'll have a look at that branch and start from there if I start working on something before your PR.

**Comment by wallento** [comment]
I think it doesn't make much sense to PR until the release as it will capture many changes. Still thinking about best strategy to split it.

One important part hidden too in the branch is the new tracing support. Maybe I will first focus on that one.

**Pull request closed without merging**
