### PR TITLE
build.py: Fix comment typo 

### PR DESCRIPTION
**Pull request by shivmgg**
Fix code comment in build script.

### CODE REVIEW

**Comment by imphil** [comment]
Thanks for this patch. Unfortunately I have the same comment as in the osd PR: Please use a commit message that describes the change, not only the "mechanics". Which files were updated is by default part of a git log, but a description of what and why was changed not -- that's that the commit message is for. So as an example, how about "Fix code comment in build script."? Please update this PR with a suitable commit message. Thanks!

**Comment by shivmgg** [comment]
Thanks for the suggestion. I will keep that in mind from now.

**Comment by imphil** [comment]
Could you please use "git commit --amend" to change the summary and push to your branch to update this PR with the updated summary?

**Comment by shivmgg** [comment]
@imphil I already did the changes yesterday.

**Comment by shivmgg** [comment]
@imphil Sorry for the confusion. Please check the changes.

**Comment by imphil** [comment]
Thanks a lot for looking also after the small changes. Your effort is very much appreciated. Looks good now, merged.

**Pull request merged**
